### ISSUE TITLE
nerd news naming

### ISSUE THREAD

**Issue by martin-przystalka** [cyryl-jaworski/nerd-news#1]
Please rename nerds news from "19-04-2024.md" to "2024-04-19.md" for proper sorting

<img width="303" alt="Screenshot 2024-04-19 at 12 28 23" src="https://github.com/cyryl-jaworski/nerd-news/assets/37142747/12137f1f-bad4-45ef-9cbe-876e7823dac1">

**Comment by cyryl-jaworski** [comment]
@martin-przystalka I trust that this resolution of the issue meets your satisfaction.
